### ISSUE TITLE
Calculating Fst and plotting the values

### ISSUE THREAD

**Issue by beausoleilmo** [malthesr/winsfs#6]
I saw that there is now support for Fst calculation with the commit named "[Add Fst](https://github.com/malthesr/winsfs/commit/edd01848f5c01ebbad187db3b99d95a592f09b67)". But I don't see how to get it from the program. 

How to get the Fst values from 2 saf files from 2 populations and plot the results in R? 

Also, when plotting the SFS values in R, is it required to remove the first and last values (e.g., `barplot(winsfs[-c(1, length(winsfs))])`, as this is what I've seen for the realSFS output)? (assume that the winsfs is the output of the program based on a saf file, the values are pasted below)

Folded: 
```
winsfs = c(128459.496517, 37807.43237, 19595.541448, 13794.172787, 11914.055373, 
11591.036125, 10717.842869, 10659.416557, 10619.180001, 9878.407667, 
9693.903963, 9162.882716, 7863.178519, 9416.350486, 8264.15024, 
7746.684849, 7423.467346, 7521.058327, 7142.004797, 7026.281412, 
6516.114025, 6935.251862, 6729.684416, 6037.666072, 6045.952302, 
6472.325573, 6216.954428, 6035.96378, 5911.554285, 6503.866442, 
6635.114531, 10348.583203, 7124.833748, 5177.385221, 4065.965662, 
4468.497129, 3837.587458, 3920.093395, 4342.735254, 3935.650826, 
4049.177171, 3887.896187, 4008.457721, 4412.583478, 4270.295593, 
4998.608504, 3509.831612, 4812.221073, 4710.699949, 4670.200019, 
4608.496482, 4876.892382, 4554.280017, 5063.93489, 5305.382852, 
5178.426539, 6011.698312, 5845.579826, 6383.94782, 7191.321642, 
7156.951056, 8282.703951, 8816.750871, 9978.439809, 11285.247227, 
13067.576935, 24704.074097, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)
```

Thanks!

**Comment by malthesr** [comment]
Thanks for your questions!

Regarding Fst: The latest main branch (see [here](https://github.com/malthesr/winsfs#current-git) for help on installing the latest git) now has a subcommand `stat` to make it easier to calculate various derived statistics from an SFS in the `winsfs` output format. So for example, `winsfs stat -s fst $sfs` would calculate the Fst for `$sfs` - see also `winsfs stat --help` for more.

Regarding plotting: It's not required to remove the fixed bins (corresponding to the first and last values) for plotting when using `winsfs` (or `realSFS` for that matter). What often happens, however, is that so much of the mass lie in these bins that all the rest of the SFS basically looks indistinguishable if they're included in the plot scale (i.e., what is usually the y-scale in 1D, or the colour/fill scale in 2D). Therefore, and since we're often mainly interested in the "shape" of the polymorphic part of the spectrum, we tend to omit the fixed bins, or include them as text instead. However, the right plotting method will depend on your data and what exactly your looking at!

**Comment by beausoleilmo** [comment]
Great! Thanks for the explanation! OK! Tested it and everything works fine with the git version! For the Est, I was thinking about per site Fst values, but it's the overall Fst for the 2 populations that is calculated. Got it!
